http:
 host: "0.0.0.0"
 port: "8082"
 path: "/api/*"
sitecore:
   host: "sitecore-integration.us-e2.cloudhub.io"
   pathOne: "/entities/575365"
   pathAll: "/search"
   methodPost: "POST"
   methodUpdate: "PUT"
application:
  name: "SiteCore System PAPI"  
  version: "1.0" 
  instanceName: "papi" 
  env: "local"
  status: "active" 
     
   
